[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting = "AsLzsAtkQaYXVJxQpWxmiY4n1Ckbo4JLpnh1EKJhWxvU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"

[test]
startup_wait = 60000
